outputDir = "../output/ ";
outputFileName = "entry1.csv";

currentFolder = pwd;
[status, cmdout] = system("cd " + pwd);
ccodepath = "../ccode/ccode/";
[status, cmdout] = system("clang++ -std=c++11 -stdlib=libc++ " + ...
    ccodepath+"main.cpp " + ...
    ccodepath+"atmospheric_model.cpp " + ...
    ccodepath+"EOM.cpp " + ...
    ccodepath+"integrator.cpp " + ...
    ccodepath+"vec_functions.cpp " + ...
    "-o ../build/to_exec");

[status, cmdout] = system("../build/to_exec " + outputDir + " " + outputFileName);
disp(cmdout)
