currentFolder = pwd;
[status, cmdout] = system("cd " + pwd);
ccodepath = "../ccode/ccode/";
[status, cmdout] = system("clang++ -std=c++11 -stdlib=libc++ " + ...
    ccodepath+"main.cpp " + ...
    ccodepath+"atmospheric_model.cpp " + ...
    ccodepath+"EOM.cpp " + ...
    ccodepath+"integrator.cpp " + ...
    ccodepath+"vec_functions.cpp " + ...
    "-o ../build/to_exec");

%% second argument is the path where we want to save the 
[status, cmdout] = system("../build/to_exec " + pwd);
disp(cmdout)
